use warnings;


$dna='CGATTACGCACTAGGTCTGGGGGTAACGCGTGTCTTGAGAAACTGAGGGCACACGTGGGTTAAGAGCTCAGAATCTTAGGGGGCCACAGATACTTCGTACACGATCTCCTCGTATCACAATCACCTTAGGCATAGGCGTGTCACGCGTTTACAGGAACCAAAACGTATTGTGACACGGCGATCTAATAGAGCAACAGAAACCTCAGGATTCGGTGACGGCGGATTGAGCATAGTTTACTTCGTGGAGGCCGCATGCACTCAACCGCTATCCGTTATACTTCAGTACCCAATTCACTGAGGATCTACATGATTCGTAAGCCAGTTATCGTGCTGGTATGCGACCGAACTCGGTCCTGGGTGCCTAAGGACATCCGCGTTACATGTCGGGGCCGTGTCTTGAAGTCCCCAGGTGGGCACGACCAGCCTTTGCCCGCAATTGGGTTTAAAGAGGCTCAGTAGGCTATCACGCGGTTTCTTTGAGGCCCGTGCATTGACAATGGTTCCCGAGAACCTGTTAGTACGCTGCCATCGCAGAGGATTTGCTGTTGTACAGGGAGTCGCTTTAAGATATCTAGCGCAAGTGAGGATTGTCCCTCACGTAGAAACAGCCCACATCCTGAGTATCCTGCCTGTGCGATTACTGTGCTCATATGATTGACGGATAATATCCTTGCCTTGAGCCGGGAGAATTCTGGCGTTGAATATACAGTGCCAGATCGCGCCCTAAGCCTAATGAGCTACCTTCCTCAAGATCAGAATCGTATGCAACTGCCTAATAATGTGGCCTGTAAACTATCTAGCACATTGCCACTCGZ';
@bases=split(//,$dna);


$ende=@bases;
%hash=();
for($i=0;$i<$ende;$i++)
{
    $nucl=$bases[$i];
    $hash{$nucl}++;
    
 
}

if (exists $hash{Z})
{print "Z ist da\n";
}

print "T ", $hash{T}, "\n";

# foreach $schluessel(sort keys%hash)
# {
#     if($schluessel eq 'Z')
#     {
# 	print "Ou ja da ist ein Z drin";
#     }
#     print "\n$schluessel ";
#     print $hash{$schluessel},"\n";
   
# }

@array=(3,7,5,1,46,18,225,4,42,5);
print "@array\n";
@arrayS=sort(@array);
print "@arrayS\n";
@arrayS=sort{$a <=> $b}(@array);
print "@arrayS\n";

@arrayS=sort{$b <=> $a}(@array);
print "@arrayS\n";


