use warnings;

$seq="TGACCCAGCACTGGCGATCTTTATCACGTAATGTACGGCAGGCTGGCCTAGATCCAGTAATGTTGTAACGCTCTACAACACTTTGCAAGGTTCTAATTACCACATGGCTGTATTCCACGCTAAAGGTACCAACCACTAAACCGACATGCTAGCTAGAATGTTCCGACAGTATGTAACGGGTGTCCTATGGATGGGGTCCGGGAACGGTTGATTGGGACAGTCCCGTCCGAGTTTCGGTCGGACTGGTGCACAACCACGGTTACAATCTCAGTAGGCTAGTAAGGTGGCATACTGGTTCGCCTTTCACATGCATGAGTGATAGTGCTCAATTCTGGCAAGTTAACAAACATAAAAGCTCCTGAGGACATCGTATCAATTGGAGAGGAGGGTAAGGAATGTGCATCCGACTGATTTGATGTCGGCGGTGCGGAGCTCCCCAAAGGTATGGTGAACGGCGTACTGACTATAACCGCGGATTTTGCGTAGTGGAGCGGTAAAGGTAGTCTCAACCCAGTTCCGACTGTCAGCCCAGCACTGAGCTACCGCAGGGCAATGGTCCTAGGGCGAGTTCCGCACTGCTTATTCAGGCTGCGCGTCCCAGGAATAGTGATGCCTTAGTCGTTATCGTACCTCGAATATCGCTACAACTGAATGGAGCGCGTTAATCGCAAATACGGGGTTGGACCTGTGGCTGAGGAGGTTTGCTGAGCATAAGTAGATGGAGCGTGGTTGAGCGCTCCGTCTATCCTTCCAGTATATAACCAACCTTCGACCGCGTTAATTCCTTAAGTCCCGCATATTACTGGGTTAGACTCCTGGATTCGCCATGAGACGGGG";


@bases=split(//,$seq);
$l=@bases;
%hash=();
       
for ($i=0;$i<$l;$i++)
{
    $nucl=$bases[$i];  #aktuelles Nukleotid
    $hash{$nucl}++;    #legt automatisch neue Buchstaben als Schlüssel an und ordnet jedem dem Wert 1 zu
    
}

foreach $schluessel(sort keys %hash)
{
    print "$schluessel ";
    print "$hash{$schluessel}\n";
}

print "\n";
