use strict;
use warnings;

my $dna='CCAGTAATACCGCTAGTTGAGCTTGATTACCTTTCGAAAAAGCTTCGGCAGCCGCGACCGTTTCAATCGCTGGCTCCGTACAATATCGTAGTTGTCGGAGCGCGATAGTTCTTGAGCGCTGCTTGCGACCCTACGCTACATTTGGACACACAACAGTGCCAGGACAATCCGCTCGATTACCCATAGTACTTATTGACTAACATCTTCGCGGGTTAAAATACTAATTACCTTATGCGCTCACGACCCGGTGGATGCCGCCACGCGACACCTGCTAGATTCAAGGAAAGTTACAGTTTCCAGGTCAGGCGACCAAACCCGCCAATCTAGTGCTACTTAGGGAAGGTTCAACATTTATAGCCCTAAACTTTAACAGGTCTACGCGTCTGGGGACACCTCAGATCAATGTACAGGAGCGTCAAGTATGGGTCCGTAAGGTCCTAAGGCACTGTTTCGATTAATTAAGAAGTGAGTTATTCATGTGACTAACTGGCCTGTCGTAGTGGTCCCAGAGTTGCTATGTGTACGTGCACTCACGGATGGTATAAGTATCGGAGAGTGCTTCCTGCTGCGAATGTCTAGAGCCTGCAGGGGTTGAGTTCCGAGAGCCAAGGTGTCCGGTGCAATCGCTAGGACGGGTGCATGATCTATGGTATATTCAGGCTATAGGGATTGCTAACTTATTTCACGGCACCGTTTGTTACGGAGCGGACCTTCTTATGCCAGCTGCTATCGGCGAAGATCGTAAGATCGGCGCCCAGGTACACCGGTCTTCGCGTGTCAGCTGAGATACAACTTATCCTATTACTAGCTCGCCTGACCTTGTTGCGT';
my @bases=split(//,$dna);
my $l=@bases;
my %hash=();

for(my $i=0;$i<$l;$i++)
{
    my $nucl=$bases[$i];
    $hash{$nucl}++;
    
}

if (exists $hash{Z})
{
    print "Z ist da!/n";
}

print "A ", $hash{A}, "\n";

foreach my $schluessel (sort keys %hash)
{
    if ($schluessel eq "A")
    {
	print "$schluessel ";
	print $hash{$schluessel},"\n";
    }
}

#@array=(3,7,5,1,46,18,225,4,42,5);
#print "@array", "\n";
#@arrayso=sort(@array);
#print "@arrayso", "\n";
#@arrayso2=sort{$a <=> $b}(@array);
#print "@arrayso2", "\n";
