use warnings;
use strict;
use functions;

my $dna="CGAGTGATCGTCACGCTCCTATGTTTTCCTGCTTTTCCGTAAGATTATTGGCGGGTTTAGCCAGCCCCAGGAGTGCGCGCCATGATTTGCCTTTCACGAATAGTTTTGTTTGGGTCCCTGTGACTGTTGTGATTTTCCGTCAATATGCTAGGGACGAGGGTTTCCCTAGCCCTGAGGTCCACTCTAACTTTGAGGAACTACAATTCCTATGCATCTCTATGAAGTCGGTGACACGGCGCAACTACCTCAACATAGGGAATTCTGATCTCTACTACACCAACAGCTGGAGCCAACTCCTCTACCTTTGGTCGATCCTGTGCATCACAATTCACCAACGTCAATAACCACCGAGAGTCAAGCCATACGAGAAAAACTCTTTGGAGCTGTCCGAAGGAATTTACTACCGTAGGAACCCTCTCCCGTACCGGAATACATCCTGCTTGTACACGGGTGTGTTTTGTGGCGAAGTGTCGTCGAACGATTCATGATCCGATGGGGCTCACTCCCTTGCCCGTAGTCAAGCTCCTGATGGTTTCGGCCCGATGCTAGCTACTGGTTCTATCCGTGGTTCCAAACTTGCTTGACCCACACTCGGGAGTTATGCTGGCGCGAAATACCTTTATTGACGACCAGACCAATTCATACTTACGAAGCGCGGAGTATGCATGGGTAACAGTCGCCGCGCATTCGTGTTAGAGTATCTAACAACGAGACTTCTTTTCGATAGTCTATAGACGCACAAAAATCTCCCCCAATCGAACACCCCTTCACGGGTGATGCGCGGCGGCCGAAGATACTCTAAGCCTAGGGTTATTAGATTCGCGCTCCTATAGAGGTGTGGACCCTCGGCACGGGGCTAACCAGGGGGCGGTACTGTTATCACGACTTGGCTGACCTATGCTTTAGGTATTGTGCCGTCTCAGAACCTAGTAACACGTATCTCACGGCA";


#open (DNA, "sequenz2.txt") or die;
#while (<DNA>)
#{
#    $dna=$dna$_;
#}
#close (DNA);

#my @dna_array = split(//, $dna);

#my @rna_array = &functions::replace_bases(\@dna_array);
#print @rna_array,"\n";

#print $dna, "\n";
print &functions::transkription($dna), "\n";
